import AddRide from "./APIs/AddRide.mjs";
import DeleteRide from "./APIs/DeleteRide.mjs";
import GetRides from "./APIs/GetRides.mjs";
import UpdateRide from "./APIs/UpdateRide.mjs";
import Signin from "./APIs/Signin.mjs";
import UpdateUser from "./APIs/UpdateUser.mjs";
import DeleteUser from "./APIs/DeleteUser.mjs";
import GetUsers from "./APIs/GetUsers.mjs";
import GetAdminData from "./APIs/GetAdminData.mjs";
import GetUser from "./APIs/GetUser.mjs";
import AddDriverRate from "./APIs/AddDriverRate.mjs";
import GetClientPoints from "./APIs/GetClientPoints.mjs";
import GetRatings from "./APIs/GetRatings.mjs";
import SigninPhone from "./APIs/SigninPhone.mjs";

AddRide();
GetRides();
DeleteRide();
UpdateRide();
Signin();
UpdateUser();
DeleteUser();
GetUsers();
GetAdminData();
GetUser();
AddDriverRate();
GetRatings();
GetClientPoints();
SigninPhone();

