import mongoose from "mongoose";

const ClientPointsSchema = mongoose.Schema(
    {
        // _id will be auto-generated by MongoDB as ObjectId
        user_id: { type: mongoose.Schema.Types.ObjectId, required: true },
        ride_id: { type: mongoose.Schema.Types.ObjectId, ref: "rides_paye_all", required: true },
        points: { type: Number, required: true },
        points_active: { type: Number, required: true },
    },
    {
        timestamps: true
    }
)

export const ClientPointsModel = mongoose.model("clients_points_paye_all", ClientPointsSchema, 'clients_points');

