import mongoose from "mongoose";

const DriversRateSchema = mongoose.Schema(
    {
        // _id will be auto-generated by MongoDB as ObjectId
        user_id: { type: mongoose.Schema.Types.ObjectId, required: true },
        ride_id: { type: mongoose.Schema.Types.ObjectId, required: true },
        driver_id: { type: mongoose.Schema.Types.ObjectId, required: true },
        description: { type: String },
        rate: { type: Number, required: true },
        rate_active: { type: Number, required: true },
    },
    {
        timestamps: true
    }
)

export const DriversRateModel = mongoose.model("drivers_rate_paye_all", DriversRateSchema, 'drivers_rate');

