import mongoose from "mongoose";

const RatingsSchema = mongoose.Schema(
    {
        // _id will be auto-generated by MongoDB as ObjectId
        rater_id: { type: mongoose.Schema.Types.ObjectId, ref: "users_paye_all", required: true },
        ride_id: { type: mongoose.Schema.Types.ObjectId, ref: "rides_paye_all", required: true },
        rated_id: { type: mongoose.Schema.Types.ObjectId, ref: "users_paye_all", required: true },
        description: { type: String },
        rate: { type: Number, required: true }, // rate for the driver/client (1 - 6) 1 means the driver/client was not even present
        rate_active: { type: Number, required: true },
    },
    {
        timestamps: true
    }
)

export const RatingsModel = mongoose.model("ratings_paye_all", RatingsSchema, 'ratings');

