import mongoose from "mongoose";

const UserSchema = mongoose.Schema(
    {
        // _id will be auto-generated by MongoDB as ObjectId
        names: { type: String, required: true },
        gender: { type: Number },
        country: { type: String },
        city: { type: String, required: true },
        state: { type: String },
        address: { type: String },
        phone_numbers: { type: [String], default: [] },
        user_email: { type: String, required: true, unique: true },
        user_emails: { type: [String], default: [] },
        apple_id: { type: String, unique: true }, // Optional Apple ID for Sign in with Apple
        user_password: { type: String },
        profile_picture: { type: String },
        account_type: { type: Number },
        is_admin: { type: Boolean, default: false },
        // Car information (for drivers)
        car_model: { type: String },
        car_condition: { type: Number }, // 0 = excellent, 1 = good/fair, 2 = poor/scrap
        license_plate: { type: String },
        car_number: { type: String },
        insurance_details: { type: String },
        insurance_number: { type: String },
        notification_token: { type: String },
        ask_become_driver: { type: Boolean, default: false },
    },
    {
        versionKey: false,
        timestamps: true
    }
)

export const UserModel = mongoose.model("users_paye_all", UserSchema, 'users');

